- tools/NewslettersSummaryConsole/Core/HtmlExtractor.cs
- tools/NewslettersSummaryConsole/Core/Interfaces/ISummaryFileService.cs
- tools/NewslettersSummaryConsole/Core/TextSplitter.cs
- tools/NewslettersSummaryConsole/Infrastructure/Email/EmailProcessor.cs
- tools/NewslettersSummaryConsole/Infrastructure/Files/SummaryFileService.cs
- tools/NewslettersSummaryConsole/Infrastructure/Prompts/EmailSummaryPrompt.cs
- tools/NewslettersSummaryConsole/Infrastructure/Summarizers/OllamaSummarizer.cs
- tools/NewslettersSummaryConsole/NewslettersSummaryConsole.csproj
- tools/NewslettersSummaryConsole/Program.cs
This pull request introduces several enhancements and refactoring to improve the email processing and summarization functionality in the `NewslettersSummaryConsole` project. The key changes include the addition of HTML content extraction, text splitting for large emails, and improved handling of email summaries.
* [`tools/NewslettersSummaryConsole/Core/HtmlExtractor.cs`](diffhunk://#diff-de06fec71ce71fbee5c7cd8bf0a7601240993bdf82d380a445275a28abe49a61R1-R47): Added a new `HtmlExtractor` class to clean and extract text from HTML content, removing scripts and styles, decoding HTML entities, and cleaning the text.
* [`tools/NewslettersSummaryConsole/Core/TextSplitter.cs`](diffhunk://#diff-95fe7185f369c9fe98f0d5b227b12dbd88c9f429ef8eadfe2a5fdfe9697585dcR1-R97): Introduced a `TextSplitter` …
> feat: extracting text from html

- tools/NewslettersSummaryConsole/Core/Interfaces/IEmailProcessor.cs
- tools/NewslettersSummaryConsole/Core/Services/EmailService.cs
- tools/NewslettersSummaryConsole/Infrastructure/Email/EmailProcessor.cs
- tools/NewslettersSummaryConsole/Infrastructure/Files/SummaryFileService.cs
- tools/NewslettersSummaryConsole/Infrastructure/Prompts/EmailSummaryPrompt.cs
- tools/NewslettersSummaryConsole/Infrastructure/Summarizers/ClaudeSummarizer.cs
- tools/NewslettersSummaryConsole/Program.cs
This pull request introduces several enhancements to the email processing system, primarily focusing on summarizing and displaying processed emails. The changes include adding a new method to display a summary of processed emails, modifying the file path structure for saved summaries, and updating the summarization prompt format. 
Key changes:
* Added a new method `DisplayProcessedEmailsSummary` to the `IEmailProcessor` interface and its implementation in `EmailProcessor` to display a summary of processed emails. This method includes a formatted output of processed email details. [[1]](diffhunk://#diff-804f7b08aa4d0a654a2a0c6be93501d31b585ae17a0946b66a6f9043ad5f4c5aR9) [[2]](diffhunk://#diff-15a6ae435a1b5ee9b9c078192a02e8aed93f486028f77bcaa4611e03dcd29f4aR87-R126)
* Updated the …
> refactor: improved prompt and claude summarizer

- .cursor/rules/001-tdd-as-if-you-meant-it.mdc
- .cursor/rules/010-csharp-tdd..mdc
- .cursor/rules/020-agent-macros.mdc
- .cursor/rules/030-agent-tdd.mdc
Added cursor rules. Inspired by this video: https://www.youtube.com/watch?v=TJZ9w863mS0
> chore: added cursor rules

- sandbox/cybersecurity/cryptography/HistoricalCiphersDemo/Ciphers/Vigenère/VigenèreCipher.cs
- sandbox/cybersecurity/cryptography/HistoricalCiphersDemo/Program.cs
- sandbox/cybersecurity/cryptography/HistoricalCiphersDemo/README.md
- sandbox/cybersecurity/cryptography/HistoricalCiphersDemo/Tests/VigenèreCipherTests.cs
Added Vigenère cipher to `HistoricalCipherDemo`
> feat: added Vigenère cipher

- .github/workflows/rss-feed.yml
- website/.gitignore
- website/About.md
- website/Contact.md
- website/Garage.md
- website/Garage/Changelog/01/How to implement custom RSS feed for website hosted on Obsidian Publish.md
- website/Garage/Cryptography/Key definitions/Plaintext.md
- website/Garage/Cryptography/symmetric encryption/Data Encryption Standard (DES).md
- website/Garage/Cybersecurity/Historical cryptography algorithms.md
- website/Garage/Frontend.md
- website/Garage/Frontend/Graphql/How to use GraphQL mutations in React and Apollo Client.md
- website/Garage/Frontend/Graphql/Introduction to the Apollo local state and reactive variables.md
- website/Garage/Frontend/React/React Context API - It Is Not as Difficult as You Think.md
- website/e2e/links.spec.js
- website/feed.xml.js
- website/feed.xml.test.js
- website/jest.config.js
- website/package-lock.json
- website/package.json
- website/playwright.config.ts
- improved RSS feed generating
- added unit tests for RSS feed generator
- added e2e tests for checking links 
Enhancements to RSS feed and testing:
* [`.github/workflows/rss-feed.yml`](diffhunk://#diff-57a4406c21c5ccb805051a204b1f6413a2a6e2748e90304782237f211f71cbbeL1-R13): Updated the workflow to include unit tests, e2e tests, and uploading test results. Renamed the job to `build-test-and-deploy` and added paths for `.js` and `.json` files. [[1]](diffhunk://#diff-57a4406c21c5ccb805051a204b1f6413a2a6e2748e90304782237f211f71cbbeL1-R13) [[2]](diffhunk://#diff-57a4406c21c5ccb805051a204b1f6413a2a6e2748e90304782237f211f71cbbeR35-R58)
Content and formatting improvements:
* [`website/About.md`](diffhunk://#diff-8311e15417d3d86c67ac85502ef6396abe120fe3b5326bc3be7641857966711dL3-R3): Reorganized …
> refactor: improved RSS feeds

- website/Garage/Changelog/01/I migrated website from Astro.build to Obsidian publish.md
- website/Garage/Changelog/Garage changelog 01.md
- website/Garage/Frontend/Graphql/How to create a quick search component using Apollo lazy query.md
+ corrected date in `website/Garage/Frontend/Graphql/How to create a quick search component using Apollo lazy query.md` article
> feat: added post about migrating blog from astro to obsidian publish

- .gitignore
- tools/NewslettersSummaryConsole/README.md
- tools/NitroDigest/.env.example
- tools/NitroDigest/README.md
- tools/NitroDigest/__tests__/__init__.py
- tools/NitroDigest/__tests__/test_email_processor.py
- tools/NitroDigest/__tests__/test_html_extractor.py
- tools/NitroDigest/__tests__/test_summarizer.py
- tools/NitroDigest/__tests__/test_summary_writer.py
- tools/NitroDigest/email_processor.py
- tools/NitroDigest/html_extractor.py
- tools/NitroDigest/main.py
- tools/NitroDigest/prompt.py
- tools/NitroDigest/prompt_template.txt
- tools/NitroDigest/pytest.ini
- tools/NitroDigest/requirements.txt
- tools/NitroDigest/summarizer.py
- tools/NitroDigest/summary_writer.py
- website/ADR.md
- website/ADR/ADR001 - Programming language for the Garage project.md
- website/Garage/Changelog/Garage changelog 2025.2.md
Plus added the first ADR about using Python as the main language in the repository.
- deprecated `NewslettersSummaryConsole` .Net project
- created new `NewslettersSummaryConsole` Python project
> feat: NitroDigest kickoff

- tools/NitroDigest/.env.example
- tools/NitroDigest/.gitignore
- tools/NitroDigest/README.md
- tools/NitroDigest/docker-compose.ollama.yml
- tools/NitroDigest/main.py
- tools/NitroDigest/ollama/Modelfile
- tools/NitroDigest/ollama/docker-compose.ollama.yml
- tools/NitroDigest/ollama/run_ollama.sh
- tools/NitroDigest/prompt_template.txt
- added docker-compose setup for Ollama (API, and Web UI)
- updated readme 
- fixed configuration naming bugs
- updated default prompt template
> feat(#65). Added docker setup for local Ollama

- tools/NitroDigest/README.md
Update readme regarding gmail set up for NitroDigest.
> chore(NitroDigest): gmail setup notes

- tools/NitroDigest/main.py
Move defaults to where arguments are defined.
> chore(NitroDigest): move defaults to args definitions

- website/Changelog.md
- website/Journals/2. 2025-04-19.md
- website/Journals/4. 2025-04-22 - continue.md
New journal + small changes in changelog
> chore: journal - 22-04-2025 - tried to get back to work after holiday

- website/.gitignore
- website/Changelog.md
- website/Journals/8. 2025-04-25 - CLI tools research.md
Plus added .*draft.md to .gitignore so I can now work on drafts without stashing changes when committing different files.
> chore: journal 26-04-2025 -> CLI tools research

- sandbox/python/level0-python-basics/python-tutorial-notes.ipynb
- sandbox/python/level0-python-basics/testfile.txt
- input & output
- exceptions
- base notes about classes
> feat: updated python tutorial notes

- website/Changelog.md
- website/Garage/Notes/Notes from CLIG.md
- website/Journals/12. 2025-04-29 - design for NitroDigest CLI.md
plus fixed one typo in previous journal
> chore: journal about designing NitroDigest CLI tool

- Projects/Nitrodigest/Cli/setup.cfg
- Projects/Nitrodigest/Cli/src/__init__.py
I tried to fix "No module named 'main' error.
> fix: wrong entrypoint

- .github/workflows/garage_static_code_analysis.yml
- .github/workflows/nitrodigest_publish.yml
- .github/workflows/rss-feed.yml
> build: added permissions to worflows

- Atlas/Books.md
- Atlas/Engineering/Cybersecurity/Cybersecurity learning roadmap.md
- Atlas/Engineering/Databases/Database Systems and MySQL learning roadmap.md
- Atlas/Engineering/Internet of things/Internet of things learning roadmap.md
- Atlas/Engineering/Machine Learning/Machine learning roadmap.md
- Atlas/Engineering/Programming/Programming Mastery Roadmap.md
And added new roadmap for programming
> chore:  added info about AI to roadmaps

- Projects/Nitrodigest/Docs/Guides/Summarizing All Files in a Directory.md
- Projects/Nitrodigest/Docs/NitroDigest – Documentation.md
- Projects/Nitrodigest/Journals/13. Creating docs.md
docs: added guide about how to summarize files in directory
Described how to use NitroDigest for summarizing files in one directory.
Also updated journal and fixed small type in docs main page
> docs: added guide about how to summarize files in directory

- Projects/Nitrodigest/Docs/Guides/Overriding Prompt Templates.md
- Projects/Nitrodigest/Journals/13. Creating docs.md
Described how to overwrite default prompt and showed possible configuration options
> docs: guide for prompting

- Atlas/Books.md
- Projects/Nitrodigest/Docs/Guides/Understanding the Output Format.md
- Projects/Nitrodigest/Docs/Guides/Using a Custom Configuration.md
- added guide about configuration 
- and output format
- also added ML book to ML learning roadmap
> docs: guides about configuration and output

- Atlas/Engineering/Machine Learning/Level 0 - Python basics/Basic Python Programs/Basic Python Programs for learning purposes.md
- Atlas/Engineering/Machine Learning/Level 0 - Python basics/Basic Python Programs/Engine‑power conversion/README.md
- Atlas/Engineering/Machine Learning/Level 0 - Python basics/Basic Python Programs/Engine‑power conversion/main.py
- Atlas/Engineering/Machine Learning/Level 0 - Python basics/Basic Python Programs/Fuel Consumption Analysis/README.md
- Atlas/Engineering/Machine Learning/Machine learning roadmap.md
Simple python program that converts horsepower to kilowatts and vice versa
> feat: resolved second excercise from basic python tasks

- Projects/Nitrodigest/setup.cfg
- Projects/Nitrodigest/src/cli/__init__.py
- Projects/Nitrodigest/src/cli/main.py
Added log when there is an error during processing directory, and replaced `print` with `logger` in the `main.py` file.
fixes #157
> fix(#157): show error when processing directory

- Projects/Nitrodigest/src/scripts/fetch_gh_prs.py
Added script that fetch PRs to directory and afterwords, when I have PRs on my machine, I can summarize them using nitrodigest.
> feat: added script for fetching pull requests from github

- .pymarkdown
- Projects/Nitrodigest/Docs/Use Cases/Summarizing GitHub Pull Requests.md
- Projects/Nitrodigest/Docs/Use Cases/Summarizing Web Pages.md
Summarizing GitHub pull requests using GH cli and Nitrodigest.
> docs: added guide about how to summarize GH pull requests

- Blog/2025/Why I built my own RSS feed generator for the Obsidian Publish website.md
RSS feed generation as broken becase of outdated link.
> fix: fixed broken link

- Blog.md
- Blog/2025/How I failed at writing a blog many times and what I would do differently if I could turn back time.md
- Blog/2025/How and why I moved my blog from WordPress to Astro and Markdown.md
- Blog/2025/How saying ‘I don’t know’ can make You a better Software Engineer.md
- Blog/2025/Onboarding to coding after being a tech leader for 4 years.md
- Blog/2025/What well-known life laws I confirmed when I did a kitchen renovation.md
- Blog/2025/Why teaching kids how to program is not easy.md
Migrated a few posts from Medium
> chore: migrated posts from Medium
